pool:
  vmImage: 'ubuntu-latest'

trigger: none

schedules:
  - cron: '0 12 * * *'
    displayName: 'Trigger dependency analysis'
    branches:
      include:
        - master
    always: true

steps:
  - task: dependabot@1
