GET http://localhost:8080/actuator/health

###

GET http://localhost:8080/customers

###

POST http://localhost:8080/customers HTTP/1.1
content-type: application/json

{
    "CustomerName": "Testing"
}
